### ISSUE TITLE
Don't return matplotlib module

### ISSUE THREAD

**Issue by jmoberreuter** [chrispaulca/hosted_waterfall#15]
I guess you want to end waterfall.py with "return fig". Now you are returning the matplotlib module rather than the figure.

**Comment by chrispaulca** [comment]
Thanks for raising this issue jmoberreuter, you are absolutely correct. User noklam went ahead and made the appropriate edit and I've now merged this change into master. I will be updating the PyPI hosted version soon. Thanks!
